require 'support/contexts/api/endpoints'
require 'support/contexts/api/yammer_get'
require 'support/contexts/api/yammer_post'
require 'support/contexts/api/yammer_put'
require 'support/contexts/api/yammer_delete'
